### ISSUE TITLE
Any plans to use a lua http lib in future?

### ISSUE THREAD

**Issue by ellisonleao** [hkupty/daedalus.nvim#4]
Thanks for the awesome plugin. I was wondering if you have any plans to move from curl to a lua http lib to handle the requests, like [lua-http](https://github.com/daurnimator/lua-http) for instance.

**Comment by hkupty** [comment]
Yes, in fact, I plan on having curl as an option, as well as other alternatives such as lua-http.

I don't want to bundle dependencies, so it'll try to pick up the best choice available, falling back to curl if none.

Thanks for the suggestion and I'm really glad you like it!
I'll keep this open until I implement lua-http support.

Best regards,
Henry

**Comment by ellisonleao** [comment]
Thanks! If you need any assistance i am definitely willing to help on this

**Comment by hkupty** [comment]
I always enjoy when pull requests come in, so if you're feeling adventurous I'd encourage you to try and hack.

We can eventually elaborate further, but I'm afraid daedalus is still touching the basics when it comes to http requests so pretty much anything will be an improvement already :)
